[package]
name = "hello"
version = "1.0.0"
description = "Hello World example package for AetherLang"
authors = ["J-x-Z"]
license = "MIT"
repository = "https://github.com/J-x-Z/aether-packages"

[build]
main = "src/main.aeth"
